name: event_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

    # Package
  smooth_page_indicator: ^1.2.0+3
  percent_indicator: ^4.2.3
  iconsax: ^0.0.8
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/onBoarding/
    - Assets/onBoarding/OnBoarding2/
    - Assets/onBoarding/OnBoarding3/
    - Assets/logos/
    - Assets/person/
    - Assets/icons/
    - Assets/getStarted/
